apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-application-properties
data:
  application.properties: |
    apse.tls.store.truststore.file=""
    apse.tls.store.producer.file=""
    apse.tls.store.consumer.hostNameVerifySkipList=""
    apse.tls.store.consumer.file=""

    {{- range .Values.endpoints  }}
    {{- $name := .name }}

    apse.endpoint.inbound.{{ $name }}={{ .inboundUrl }}
      {{- range .outbounds  }}
    apse.endpoint.outbound.{{ $name }}.{{ regexReplaceAll "^.*(apotekens)" (.namespace | replace ":" ".")  "$1" }}={{ .url }}


      {{- end }}
    {{ end }}

    apse.endpoint.connect.timeout=2000