apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-configmap
data:
  application.properties: |
    {{- range .Values.endpoints  }}
    {{- $name := .name }}

    apse.endpoint.inbound.{{ $name }}={{ .inboundUrl }}
      {{- range .outbounds  }}
    apse.endpoint.outbound.{{ $name }}.{{ regexReplaceAll "^.*(apotekens)" (.namespace | replace ":" ".")  "$1" }}={{ .url }}


      {{- end }}
    {{ end }}

    apse.endpoint.connect.timeout=2000
    
    #debug
    locatorLabelApseAdapt=Castor
    locatorLabelTicketMachine=Pollux
    locatorLabelGeneral=Polaris