apiVersion: apps/v1
kind: Deployment
metadata:
  name: apse-adapter
  labels:
    {{- include "apse-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "apse-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: apse-adapter
        {{- include "apse-adapter.selectorLabels" . | nindent 8 }}
        elasticGrokFilter: {{ .Values.deployment.elasticGrokFilter }}
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: application-properties-configmap
        {{- if .Values.trust.anchorSecret.name }}
        - name: truststore
          secret:
            secretName: {{ .Values.trust.anchorSecret.name }}
            items:
              - key: {{ .Values.trust.anchorSecret.key }}
                path: ca.crt
        {{- end }}
        - name: log4j
          configMap:
            name: log4j2-configmap

      imagePullSecrets:
        - name: regcred

      containers:
        - name: apse-adapter
          image: {{ .Values.repository }}apse-adapter:{{ .Values.container.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http2
              containerPort: 11009
              protocol: TCP
            - name: http-tj-bryggan
              containerPort: 11005
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: actuator/health/liveness
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: actuator/health/readiness
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000 # ind-app
            seccompProfile:
              type: RuntimeDefault
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- with .Values.environment.variables }}
          {{- if .map }}
          env:
            {{- range $k, $v := .map }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            {{- range $.Values.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range $.Values.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}

          volumeMounts:
            - name: application-properties
              mountPath: /opt/apse/config/application-properties
              readOnly: true
            - name: log4j
              mountPath: /opt/apse/config/log4j
              readOnly: true
              {{- if .Values.trust.anchorSecret.name }}
            - name: truststore
              mountPath: {{ .Values.trust.anchorMountPath }}
              readonly: true
              {{- end }}
