apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-configmap
data:
  java.opts: " -Duser.country=SE -Duser.language=en -Xms512m -Xmx1536m -XX:MaxMetaspaceSize=256m -XX:CompressedClassSpaceSize=256m"
  spring.profiles.include: "security"
  camel.springboot.name: "ApSeAdapter"

  ## ApSE
  apse.host: "0.0.0.0"
  apse.port: "8080"
  apse.status.url: "http://${apse.host}:${apse.port}/status"
  # Response size in bytes (15Mb=15*1024*1024)
  apse.max.receive.length: "15728640"

  # Turn on actuator health check
  endpoints.health.enabled: "true"

  ## MANAGEMENT ##
  # Allow to obtain basic information about camel routes (read only mode)
  management.camelroutes.enabled: "true"
  management.camelroutes.read-only: "true"

  # show verbose health details (/actuator/health) so you can see Camel information also
  management.endpoint.health.show-details: "always"
  management.endpoints.web.exposure.include: "info,health"
  management.health.enabled: "true"

  # to turn off Camel info in (/actuator/info)
  management.info.camel.enabled: "true"
  management.info.camel.verbose: "true"
  
  # All access to actuator endpoints without security
  management.security.enabled: "false"

  ## OTHER
  memory.logger.period.seconds: "120"
  producer.http.connect.timeout: "5000"
  producer.https.connect.timeout: "5000"
  classpath: /opt/apse/config/application-properties

  # Used for actuator
  server.port: "8089"

  # Key where to find senderid in certificates subject
  certificate.senderid.subject.pattern: "OU=([^,]+)"


  ## LOGGING LEVELS
  APSE_REQ_IN_LOGLEVEL: DEBUG
  APSE_REQ_OUT_LOGLEVEL: DEBUG
  APSE_RESP_IN_LOGLEVEL: DEBUG
  APSE_RESP_OUT_LOGLEVEL: DEBUG
  APSE_ERROR_LOGLEVEL: DEBUG
