apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-configmap
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="">
      <Appenders>
      <Console name="Console">
        <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
      </Console>
      </Appenders>
      <Loggers>
        <Logger name="se.skltp.adapterservices.apse" level="DEBUG" additivity="false">
          <AppenderRef ref="Console"/>
        </Logger>
        <Logger name="se.skltp" level="INFO" additivity="false">
          <AppenderRef ref="Console"/>
        </Logger>
        <Root level="WARN">
          <AppenderRef ref="Console"/>
        </Root>
      </Loggers>
    </Configuration>