apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-configmap
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="">
      <Appenders>
      <Console name="Console">
        <EcsLayout/>
      </Console>
      </Appenders>
      <Loggers>
        {{- range .Values.log4j.loggers }}
        <AsyncLogger name="{{ .name }}" level="{{ .level }}"/>
        {{- end }}
    
        <AsyncRoot level="{{ .Values.log4j.rootLoggerLevel }}">
          <AppenderRef ref="Console"/>
        </AsyncRoot>
      </Loggers>
    </Configuration>