apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vip.name }}
  labels:
    {{- include "apse-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11005
      targetPort: http
      protocol: TCP
      name: http-tj-bryggan
    - port: 11009
      targetPort: http
      protocol: TCP
      name: http2
  selector:
    {{- include "apse-adapter.selectorLabels" . | nindent 4 }}