apiVersion: v1
kind: Service
metadata:
  name: apse-adapter
  labels:
    {{- include "apse-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apse-adapter.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: ind-dtjp-anp-vip
  labels:
    {{- include "apse-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11005
      targetPort: http
      protocol: TCP
      name: http1
    - port: 11009
      targetPort: http
      protocol: TCP
      name: http2
  selector:
    {{- include "apse-adapter.selectorLabels" . | nindent 4 }}