apiVersion: v1
kind: Service
metadata:
  name: apse-adapter
  labels:
    {{- include "apse-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apse-adapter.selectorLabels" . | nindent 4 }}