repository: docker.drift.inera.se/ntjp/
replicaCount: 1

container:
  image:
    tag: # Nothing yet. Override to supply your own values.
    pullPolicy: Always

# Environment-specific backwards-compatible service name
vip:
  name: default-anp-vip

environment:
  variables:
    _default_config_maps:
      - application-properties-configmap
      - environment-configmap
      - log4j2-configmap
    config_maps:
      # Nothing yet. Override to supply your own values.
    secrets:
      # Nothing yet. Override to supply your own values.

initContainer:
  certGen:
    image:
      name: cert-generator-utility
      tag: 4.3.2-RC2-SNAPSHOT

pem_to_pfx:
  envPrefix: PEM2PFX
  pem:
    path: /opt/certs/pem
  pfx:
    path: /opt/certs/pkcs12
  trust:
    secretName: esb-function-cert
    pemFile: ca.pem
    pfxFile: truststore.pfx
    password: password
  producer:
    secretName: esb-function-cert
    pemCertFile: producer.crt
    pemKeyFile: producer.key
    pfxFile: producer.pfx
    password: password
  consumer:
    secretName: test.esb.ntjp.sjunet.org
    pemCertFile: consumer.crt
    pemKeyFile: consumer.key
    pfxFile: consumer.pfx
    password: password