repository: docker.drift.inera.se/ntjp/

deployment:
  replicaCount: 1
  elasticGrokFilter: camel

container:
  image:
    tag: # Nothing yet. Override to supply your own values.
    pullPolicy: Always

# Environment-specific backwards-compatible service name
vip:
  name: default-anp-vip

environment:
  variables:
    _default_config_maps:
      - application-properties-configmap
      - environment-configmap
      - log4j2-configmap
    config_maps:
      # Nothing yet. Override to supply your own values.
    secrets:
      # Nothing yet. Override to supply your own values.

trust:
  anchorMountPath: /etc/pki/ca-trust/source/anchors
  anchorSecret:
    name:
    key: ca.crt


endpoints:
  - name: nmtstubs
    inboundUrl: http://0.0.0.0:11005/tjanstebryggan
    outbounds:
      - namespace: apotekensservice.axs.HamtaPatientInfoResponder.6
        url: https://load-mocks.sm.nordicmedtest.se/HamtaPatientInfoResponder/V6
      - namespace: urn:riv:se.apotekensservice.axs.HamtaPatientInfoResponder.5
        url: https://load-mocks.sm.nordicmedtest.se/HamtaPatientInfoResponder/V5
